const countries = [
  {
    code: 'AF',
    name: 'Afghanistan',
    turkishName: 'Afganistan',
    zone: 4,
  },
  {
    code: 'AL',
    name: 'Albania',
    turkishName: 'Arnavutluk',
    zone: 4,
  },
  {
    code: 'DZ',
    name: 'Algeria',
    turkishName: 'Cezayir',
    zone: 6,
  },
  {
    code: 'AS',
    name: 'American Samoa',
    turkishName: 'Amerikan Samoası',
    zone: 8,
  },
  {
    code: 'AD',
    name: 'Andorra',
    turkishName: 'Andorra',
    zone: 4,
  },
  {
    code: 'AO',
    name: 'Angola',
    turkishName: 'Angola',
    zone: 9,
  },
  {
    code: 'AI',
    name: 'Anguilla',
    turkishName: 'Anguilla',
    zone: 8,
  },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    turkishName: 'Antigua ve Barbuda',
    zone: 8,
  },
  {
    code: 'AR',
    name: 'Argentina',
    turkishName: 'Arjantin',
    zone: 8,
  },
  {
    code: 'AM',
    name: 'Armenia',
    turkishName: 'Ermenistan',
    zone: 4,
  },
  {
    code: 'AW',
    name: 'Aruba',
    turkishName: 'Aruba',
    zone: 8,
  },
  {
    code: 'AU',
    name: 'Australia',
    turkishName: 'Avustralya',
    zone: 7,
  },
  {
    code: 'AT',
    name: 'Austria',
    turkishName: 'Avusturya',
    zone: 4,
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    turkishName: 'Azerbaycan',
    zone: 4,
  },
  {
    code: 'BS',
    name: 'Bahamas',
    turkishName: 'Bahamalar',
    zone: 8,
  },
  {
    code: 'BH',
    name: 'Bahrain',
    turkishName: 'Bahreyn',
    zone: 4,
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    turkishName: 'Bangladeş',
    zone: 7,
  },
  {
    code: 'BB',
    name: 'Barbados',
    turkishName: 'Barbados',
    zone: 8,
  },
  {
    code: 'BY',
    name: 'Belarus',
    turkishName: 'Belarus',
    zone: 4,
  },
  {
    code: 'BE',
    name: 'Belgium',
    turkishName: 'Belçika',
    zone: 2,
  },
  {
    code: 'BZ',
    name: 'Belize',
    turkishName: 'Belize',
    zone: 8,
  },
  {
    code: 'BJ',
    name: 'Benin',
    turkishName: 'Benin',
    zone: 9,
  },
  {
    code: 'BM',
    name: 'Bermuda',
    turkishName: 'Bermuda',
    zone: 8,
  },
  {
    code: 'BT',
    name: 'Bhutan',
    turkishName: 'Butan',
    zone: 7,
  },
  {
    code: 'BO',
    name: 'Bolivia',
    turkishName: 'Bolivya',
    zone: 8,
  },
  {
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    turkishName: 'Bonaire, Sint Eustatius ve Saba',
    zone: 8,
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    turkishName: 'Bosna Hersek',
    zone: 4,
  },
  {
    code: 'BW',
    name: 'Botswana',
    turkishName: 'Botsvana',
    zone: 9,
  },
  {
    code: 'BR',
    name: 'Brazil',
    turkishName: 'Brezilya',
    zone: 8,
  },
  {
    code: 'VG',
    name: 'British Virgin Islands',
    turkishName: 'İngiliz Virgin Adaları',
    zone: 8,
  },
  {
    code: 'BN',
    name: 'Brunei',
    turkishName: 'Brunei',
    zone: 7,
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    turkishName: 'Bulgaristan',
    zone: 2,
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    turkishName: 'Burkina Faso',
    zone: 9,
  },
  {
    code: 'BI',
    name: 'Burundi',
    turkishName: 'Burundi',
    zone: 9,
  },
  {
    code: 'KH',
    name: 'Cambodia',
    turkishName: 'Kamboçya',
    zone: 7,
  },
  {
    code: 'CM',
    name: 'Cameroon',
    turkishName: 'Kamerun',
    zone: 9,
  },
  {
    code: 'CA',
    name: 'Canada',
    turkishName: 'Kanada',
    zone: 5,
  },
  {
    code: 'CV',
    name: 'Cape Verde',
    turkishName: 'Cape Verde',
    zone: 9,
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
    turkishName: 'Cayman Adaları',
    zone: 8,
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    turkishName: 'Orta Afrika Cumhuriyeti',
    zone: 9,
  },
  {
    code: 'TD',
    name: 'Chad',
    turkishName: 'Çad',
    zone: 9,
  },
  {
    code: 'CL',
    name: 'Chile',
    turkishName: 'Şili',
    zone: 8,
  },
  {
    code: 'CN',
    name: 'China',
    turkishName: 'Çin',
    zone: 6,
  },
  {
    code: 'CO',
    name: 'Colombia',
    turkishName: 'Kolombiya',
    zone: 8,
  },
  {
    code: 'KM',
    name: 'Comoros',
    turkishName: 'Komorlar',
    zone: 9,
  },
  {
    code: 'CG',
    name: 'Congo',
    turkishName: 'Kongo',
    zone: 9,
  },
  {
    code: 'CK',
    name: 'Cook Islands',
    turkishName: 'Cook Adaları',
    zone: 9,
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    turkishName: 'Kosta Rika',
    zone: 8,
  },
  {
    code: 'CI',
    name: "Côte d'Ivoire",
    turkishName: 'Fildişi Sahili',
    zone: 9,
  },
  {
    code: 'HR',
    name: 'Croatia',
    turkishName: 'Hırvatistan',
    zone: 4,
  },
  {
    code: 'CW',
    name: 'Curaçao',
    turkishName: 'Curaçao',
    zone: 8,
  },
  {
    code: 'CY',
    name: 'Cyprus',
    turkishName: 'Kıbrıs Rum Kesimi',
    zone: 4,
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    turkishName: 'Çekya',
    zone: 3,
  },
  {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    turkishName: 'Kongo Demokratik Cumhuriyeti',
    zone: 9,
  },
  {
    code: 'DK',
    name: 'Denmark',
    turkishName: 'Danimarka',
    zone: 3,
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    turkishName: 'Cibuti',
    zone: 9,
  },
  {
    code: 'DM',
    name: 'Dominica',
    turkishName: 'Dominika',
    zone: 8,
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    turkishName: 'Dominik Cumhuriyeti',
    zone: 8,
  },
  {
    code: 'EC',
    name: 'Ecuador',
    turkishName: 'Ekvator',
    zone: 8,
  },
  {
    code: 'EG',
    name: 'Egypt',
    turkishName: 'Mısır',
    zone: 4,
  },
  {
    code: 'SV',
    name: 'El Salvador',
    turkishName: 'El Salvador',
    zone: 8,
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    turkishName: 'Ekvator Ginesi',
    zone: 9,
  },
  {
    code: 'ER',
    name: 'Eritrea',
    turkishName: 'Eritre',
    zone: 9,
  },
  {
    code: 'EE',
    name: 'Estonia',
    turkishName: 'Estonya',
    zone: 4,
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    turkishName: 'Etiyopya',
    zone: 9,
  },
  {
    code: 'FO',
    name: 'Faroe Islands',
    turkishName: 'Faroe Adaları',
    zone: 6,
  },
  {
    code: 'FM',
    name: 'Federated States of Micronesia',
    turkishName: 'Mikronezya Federe Devletleri',
    zone: 9,
  },
  {
    code: 'FJ',
    name: 'Fiji',
    turkishName: 'Fiji',
    zone: 9,
  },
  {
    code: 'FI',
    name: 'Finland',
    turkishName: 'Finlandiya',
    zone: 3,
  },
  {
    code: 'FR',
    name: 'France',
    turkishName: 'Fransa',
    zone: 2,
  },
  {
    code: 'GF',
    name: 'French Guiana',
    turkishName: 'Fransız Guyanası',
    zone: 8,
  },
  {
    code: 'PF',
    name: 'French Polynesia',
    turkishName: 'Fransız Polinezyası',
    zone: 9,
  },
  {
    code: 'GA',
    name: 'Gabon',
    turkishName: 'Gabon',
    zone: 9,
  },
  {
    code: 'GM',
    name: 'Gambia',
    turkishName: 'Gambiya',
    zone: 9,
  },
  {
    code: 'GE',
    name: 'Georgia',
    turkishName: 'Gürcistan',
    zone: 4,
  },
  {
    code: 'DE',
    name: 'Germany',
    turkishName: 'Almanya',
    zone: 1,
  },
  {
    code: 'GH',
    name: 'Ghana',
    turkishName: 'Gana',
    zone: 9,
  },
  {
    code: 'GI',
    name: 'Gibraltar',
    turkishName: 'Cebelitarık',
    zone: 4,
  },
  {
    code: 'GR',
    name: 'Greece',
    turkishName: 'Yunanistan',
    zone: 2,
  },
  {
    code: 'GL',
    name: 'Greenland',
    turkishName: 'Grönland',
    zone: 6,
  },
  {
    code: 'GD',
    name: 'Grenada',
    turkishName: 'Grenada',
    zone: 8,
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
    turkishName: 'Guadeloupe',
    zone: 8,
  },
  {
    code: 'GU',
    name: 'Guam',
    turkishName: 'Guam',
    zone: 9,
  },
  {
    code: 'GT',
    name: 'Guatemala',
    turkishName: 'Guatemala',
    zone: 8,
  },
  {
    code: 'GG',
    name: 'Guernsey',
    turkishName: 'Guernsey',
    zone: 4,
  },
  {
    code: 'GN',
    name: 'Guinea',
    turkishName: 'Gine',
    zone: 9,
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
    turkishName: 'Gine-Bissau',
    zone: 9,
  },
  {
    code: 'GY',
    name: 'Guyana',
    turkishName: 'Guyana',
    zone: 8,
  },
  {
    code: 'HT',
    name: 'Haiti',
    turkishName: 'Haiti',
    zone: 8,
  },
  {
    code: 'HN',
    name: 'Honduras',
    turkishName: 'Honduras',
    zone: 8,
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    turkishName: 'Hong Kong',
    zone: 6,
  },
  {
    code: 'HU',
    name: 'Hungary',
    turkishName: 'Macaristan',
    zone: 3,
  },
  {
    code: 'IS',
    name: 'Iceland',
    turkishName: 'İzlanda',
    zone: 6,
  },
  {
    code: 'IN',
    name: 'India',
    turkishName: 'Hindistan',
    zone: 6,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    turkishName: 'Endonezya',
    zone: 6,
  },
  {
    code: 'IQ',
    name: 'Iraq',
    turkishName: 'Irak',
    zone: 4,
  },
  {
    code: 'IE',
    name: 'Ireland',
    turkishName: 'İrlanda',
    zone: 2,
  },
  {
    code: 'IL',
    name: 'Israel',
    turkishName: 'İsrail',
    zone: 4,
  },
  {
    code: 'IT',
    name: 'Italy',
    turkishName: 'İtalya',
    zone: 2,
  },
  {
    code: 'JM',
    name: 'Jamaica',
    turkishName: 'Jamaika',
    zone: 8,
  },
  {
    code: 'JP',
    name: 'Japan',
    turkishName: 'Japonya',
    zone: 6,
  },
  {
    code: 'JE',
    name: 'Jersey',
    turkishName: 'Jersey',
    zone: 4,
  },
  {
    code: 'JO',
    name: 'Jordan',
    turkishName: 'Ürdün',
    zone: 4,
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    turkishName: 'Kazakistan',
    zone: 4,
  },
  {
    code: 'KE',
    name: 'Kenya',
    turkishName: 'Kenya',
    zone: 7,
  },
  {
    code: 'KI',
    name: 'Kiribati',
    turkishName: 'Kiribati',
    zone: 9,
  },
  {
    code: 'KW',
    name: 'Kuwait',
    turkishName: 'Kuveyt',
    zone: 4,
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    turkishName: 'Kırgızistan',
    zone: 4,
  },
  {
    code: 'LA',
    name: 'Laos',
    turkishName: 'Laos',
    zone: 7,
  },
  {
    code: 'LV',
    name: 'Latvia',
    turkishName: 'Letonya',
    zone: 4,
  },
  {
    code: 'LB',
    name: 'Lebanon',
    turkishName: 'Lübnan',
    zone: 4,
  },
  {
    code: 'LS',
    name: 'Lesotho',
    turkishName: 'Lesoto',
    zone: 7,
  },
  {
    code: 'LR',
    name: 'Liberia',
    turkishName: 'Liberya',
    zone: 9,
  },
  {
    code: 'LY',
    name: 'Libya',
    turkishName: 'Libya',
    zone: 6,
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    turkishName: 'Lihtenştayn',
    zone: 2,
  },
  {
    code: 'LT',
    name: 'Lithuania',
    turkishName: 'Litvanya',
    zone: 4,
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    turkishName: 'Lüksemburg',
    zone: 2,
  },
  {
    code: 'MO',
    name: 'Macao',
    turkishName: 'Makao',
    zone: 6,
  },
  {
    code: 'MK',
    name: 'Macedonia',
    turkishName: 'Makedonya (FYROM)',
    zone: 4,
  },
  {
    code: 'MG',
    name: 'Madagascar',
    turkishName: 'Madagaskar',
    zone: 9,
  },
  {
    code: 'MW',
    name: 'Malawi',
    turkishName: 'Malavi',
    zone: 9,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    turkishName: 'Malezya',
    zone: 6,
  },
  {
    code: 'MV',
    name: 'Maldives',
    turkishName: 'Maldivler',
    zone: 9,
  },
  {
    code: 'ML',
    name: 'Mali',
    turkishName: 'Mali',
    zone: 9,
  },
  {
    code: 'MT',
    name: 'Malta',
    turkishName: 'Malta',
    zone: 3,
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    turkishName: 'Marşal Adaları',
    zone: 9,
  },
  {
    code: 'MQ',
    name: 'Martinique',
    turkishName: 'Martinik',
    zone: 8,
  },
  {
    code: 'MR',
    name: 'Mauritania',
    turkishName: 'Moritanya',
    zone: 9,
  },
  {
    code: 'MU',
    name: 'Mauritius',
    turkishName: 'Morityus',
    zone: 9,
  },
  {
    code: 'YT',
    name: 'Mayotte',
    turkishName: 'Mayotte',
    zone: 9,
  },
  {
    code: 'MX',
    name: 'Mexico',
    turkishName: 'Meksika',
    zone: 5,
  },
  {
    code: 'MD',
    name: 'Moldova',
    turkishName: 'Moldova',
    zone: 4,
  },
  {
    code: 'MC',
    name: 'Monaco',
    turkishName: 'Monako',
    zone: 2,
  },
  {
    code: 'MN',
    name: 'Mongolia',
    turkishName: 'Moğolistan',
    zone: 6,
  },
  {
    code: 'ME',
    name: 'Montenegro',
    turkishName: 'Karadağ',
    zone: 4,
  },
  {
    code: 'MS',
    name: 'Montserrat',
    turkishName: 'Montserrat',
    zone: 8,
  },
  {
    code: 'MA',
    name: 'Morocco',
    turkishName: 'Fas',
    zone: 7,
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    turkishName: 'Mozambik',
    zone: 9,
  },
  {
    code: 'MM',
    name: 'Myanmar',
    turkishName: 'Myanmar',
    zone: 7,
  },
  {
    code: 'NA',
    name: 'Namibia',
    turkishName: 'Namibya',
    zone: 9,
  },
  {
    code: 'NP',
    name: 'Nepal',
    turkishName: 'Nepal',
    zone: 7,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    turkishName: 'Hollanda',
    zone: 2,
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    turkishName: 'Yeni Kaledonya',
    zone: 9,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    turkishName: 'Yeni Zelanda',
    zone: 7,
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    turkishName: 'Nikaragua',
    zone: 8,
  },
  {
    code: 'NE',
    name: 'Niger',
    turkishName: 'Nijer',
    zone: 9,
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    turkishName: 'Kuzey Mariana Adaları',
    zone: 9,
  },
  {
    code: 'NO',
    name: 'Norway',
    turkishName: 'Norveç',
    zone: 3,
  },
  {
    code: 'OM',
    name: 'Oman',
    turkishName: 'Umman',
    zone: 4,
  },
  {
    code: 'PK',
    name: 'Pakistan',
    turkishName: 'Pakistan',
    zone: 4,
  },
  {
    code: 'PW',
    name: 'Palau',
    turkishName: 'Palau',
    zone: 9,
  },
  {
    code: 'PS',
    name: 'Palestine',
    turkishName: 'Filistin',
    zone: 4,
  },
  {
    code: 'PA',
    name: 'Panama',
    turkishName: 'Panama',
    zone: 8,
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    turkishName: 'Papua Yeni Gine',
    zone: 9,
  },
  {
    code: 'PY',
    name: 'Paraguay',
    turkishName: 'Paraguay',
    zone: 8,
  },
  {
    code: 'PE',
    name: 'Peru',
    turkishName: 'Peru',
    zone: 8,
  },
  {
    code: 'PH',
    name: 'Philippines',
    turkishName: 'Filipinler',
    zone: 6,
  },
  {
    code: 'PL',
    name: 'Poland',
    turkishName: 'Polonya',
    zone: 3,
  },
  {
    code: 'PT',
    name: 'Portugal',
    turkishName: 'Portekiz',
    zone: 3,
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    turkishName: 'Porto Riko',
    zone: 5,
  },
  {
    code: 'QA',
    name: 'Qatar',
    turkishName: 'Katar',
    zone: 4,
  },
  {
    code: 'RE',
    name: 'Réunion',
    turkishName: 'Réunion',
    zone: 9,
  },
  {
    code: 'RO',
    name: 'Romania',
    turkishName: 'Romanya',
    zone: 3,
  },
  {
    code: 'RU',
    name: 'Russian Federation',
    turkishName: 'Rusya Federasyonu',
    zone: 4,
  },
  {
    code: 'RW',
    name: 'Rwanda',
    turkishName: 'Ruanda',
    zone: 9,
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    turkishName: 'Saint Barthélemy',
    zone: 8,
  },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    turkishName: 'Saint Kitts ve Nevis',
    zone: 8,
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    turkishName: 'Saint Lucia',
    zone: 8,
  },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    turkishName: 'Saint Vincent ve Grenadinler',
    zone: 8,
  },
  {
    code: 'WS',
    name: 'Samoa',
    turkishName: 'Samoa',
    zone: 9,
  },
  {
    code: 'SM',
    name: 'San Marino',
    turkishName: 'San Marino',
    zone: 4,
  },
  {
    code: 'ST',
    name: 'São Tomé and Príncipe',
    turkishName: 'Sao Tome ve Principe',
    zone: 9,
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    turkishName: 'Suudi Arabistan',
    zone: 4,
  },
  {
    code: 'SN',
    name: 'Senegal',
    turkishName: 'Senegal',
    zone: 9,
  },
  {
    code: 'RS',
    name: 'Serbia',
    turkishName: 'Sırbistan',
    zone: 4,
  },
  {
    code: 'SC',
    name: 'Seychelles',
    turkishName: 'Seyşeller',
    zone: 9,
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    turkishName: 'Sierra Leone',
    zone: 9,
  },
  {
    code: 'SG',
    name: 'Singapore',
    turkishName: 'Singapur',
    zone: 6,
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
    turkishName: 'Sint Maarten',
    zone: 8,
  },
  {
    code: 'SK',
    name: 'Slovakia',
    turkishName: 'Slovakya',
    zone: 3,
  },
  {
    code: 'SI',
    name: 'Slovenia',
    turkishName: 'Slovenya',
    zone: 3,
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    turkishName: 'Solomon Adaları',
    zone: 9,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    turkishName: 'Güney Afrika',
    zone: 7,
  },
  {
    code: 'KR',
    name: 'South Korea',
    turkishName: 'Güney Kore',
    zone: 6,
  },
  {
    code: 'ES',
    name: 'Spain',
    turkishName: 'İspanya',
    zone: 2,
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    turkishName: 'Sri Lanka',
    zone: 7,
  },
  {
    code: 'SR',
    name: 'Suriname',
    turkishName: 'Surinam',
    zone: 8,
  },
  {
    code: 'SZ',
    name: 'Swaziland',
    turkishName: 'Swaziland',
    zone: 7,
  },
  {
    code: 'SE',
    name: 'Sweden',
    turkishName: 'İsveç',
    zone: 3,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    turkishName: 'İsviçre',
    zone: 3,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    turkishName: 'Tayvan',
    zone: 6,
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    turkishName: 'Tacikistan',
    zone: 4,
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    turkishName: 'Tanzanya',
    zone: 9,
  },
  {
    code: 'TH',
    name: 'Thailand',
    turkishName: 'Tayland',
    zone: 6,
  },
  {
    code: 'TL',
    name: 'Timor-Leste',
    turkishName: 'Doğu Timor',
    zone: 9,
  },
  {
    code: 'TG',
    name: 'Togo',
    turkishName: 'Togo',
    zone: 9,
  },
  {
    code: 'TO',
    name: 'Tonga',
    turkishName: 'Tonga',
    zone: 9,
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    turkishName: 'Trinidad ve Tobago',
    zone: 8,
  },
  {
    code: 'TN',
    name: 'Tunisia',
    turkishName: 'Tunus',
    zone: 6,
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    turkishName: 'Türkmenistan',
    zone: 4,
  },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    turkishName: 'Turks ve Caicos Adaları',
    zone: 8,
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    turkishName: 'Tuvalu',
    zone: 9,
  },
  {
    code: 'UG',
    name: 'Uganda',
    turkishName: 'Uganda',
    zone: 9,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    turkishName: 'Ukrayna',
    zone: 4,
  },
  {
    code: 'AE',
    name: 'United Arab Emirates - UAE',
    turkishName: 'Birleşik Arap Emirlikleri - BAE',
    zone: 4,
  },
  {
    code: 'GB',
    name: 'United Kingdom - UK',
    turkishName: 'Birleşik Krallık - İngiltere',
    zone: 2,
  },
  {
    code: 'US',
    name: 'United States of America',
    turkishName: 'Amerika Birleşik Devletleri',
    zone: 5,
  },
  {
    code: 'VI',
    name: 'United States of America Virgin Islands',
    turkishName: 'Amerika Birleşik Devletleri Virgin Adaları',
    zone: 8,
  },
  {
    code: 'UY',
    name: 'Uruguay',
    turkishName: 'Uruguay',
    zone: 8,
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    turkishName: 'Özbekistan',
    zone: 4,
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    turkishName: 'Vanuatu',
    zone: 9,
  },
  {
    code: 'VE',
    name: 'Venezuela',
    turkishName: 'Venezuela',
    zone: 8,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    turkishName: 'Vietnam',
    zone: 7,
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    turkishName: 'Wallis ve Futuna',
    zone: 9,
  },
  {
    code: 'YE',
    name: 'Yemen',
    turkishName: 'Yemen',
    zone: 4,
  },
  {
    code: 'ZM',
    name: 'Zambia',
    turkishName: 'Zambiya',
    zone: 9,
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    turkishName: 'Zimbabve',
    zone: 9,
  },
];

export default countries;
